### ISSUE TITLE
Pre-Defined Tags Which Act As Played And Created Filter Statements

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#117]
https://github.com/terrelsa13/MUMC/issues/109#issuecomment-2155734048

> I thought about a potential enhancement to have some 'preset tags' (eg 'RetainXd' (where x could be an integer of days) for such purpose, as I would imagine some folks would find it valuable to have different retention periods on movies, shows, or even on specific series. But i'm personally not bothered by having a few containers for that purpose. But was just an idea of a potential future enhancement.

Good idea here! If I were to do something like this this generic tag would need to contain the same information a basic filter statement contains: _condition_days, count_equality, and count and way to indicate if it is for played or created filtering_. To match the current functionality.

### Optional: `filter_tags` become another form of `filter_statements`:

**filter_tags** can be added to any combination of these three locations

#### Location 1 \*RECOMMENDED\*
```yaml
basic_settings:
  filter_tags:
    media_type:
      whitetagged:
      - created:999:>=:0:false
      - played:456:not <:7
      blacktagged: [played:123:==:1,created:4321:<:2:true] 
```

#### Location 2
```yaml
advanced_settings:
  behavioral_statements:
    media_type:
      whitetags:
      - created:999:>=:0:false
      - played:456:not <:7
      blacktags: [played:123:==:1,created:4321:<:2:true] 
```

#### Location 3
```yaml
advanced_settings:
  whitetags:
  - created:999:>=:0:false
  - played:456:not <:7
  blacktags: [played:123:==:1,created:4321:<:2:true] 
```

* `created:999:>=:0:false`
   * created is the filter type
   * 999 is the condition days
   * \>= is the count equality
   * 0 is the count
   * behavioral control is false

* `played:123:==:1`
   * played is the filter type
   * 123 is the condition days
   * == is the count equality
   * 1 is the count

* `played:456:not <:7`
   * played is the filter type
   * 456 is the condition days
   * not < is the count equality
   * 7 is the count

* `created:4321:<:2:true`
   * created is the filter type
   * 4321 is the condition days
   * < is the count equality
   * 2 is the count
   * behavioral control is true

### Optional: `behavioral_tags` become another form of `behavioral_statements`:

```yaml
advanced_settings:
  behavioral_tags:
    media_type:
      created:999:>=:0:false:
        action: keep
        user_conditional: all
        played_conditional: any
        action_control: 3
        dynamic_behavior: true
        high_priority: true
      played:123:==:1:
        action: delete
        user_conditional: all
        played_conditional: ignore
        action_control: 5
        dynamic_behavior: false
        high_priority: true
      played:456:not <:7:
        action: keep
        user_conditional: all
        played_conditional: any_all
        action_control: 5
        dynamic_behavior: true
        high_priority: false
      created:4321:<:2:true:
        action: delete
        user_conditional: all
        played_conditional: all_any
        action_control: 3
        dynamic_behavior: false
        high_priority: false
```

- `behavioral_tags` are processed in the order they appear in the config
   - Like normal tags; `behavioral_whitetags` have a high priority than `behavioral_blacktags`
   - `behavioral_tags` have a higher priority than their normal tag counterparts
   - Tag priority is highest at the top; lowest at the bottom
       - The first matching `behavioral_whitetag` within a media_type has the highest priority
       - The second matching `behavioral_whitetag` within a media_type
       - etc...
       - The second to last matching `behavioral_whitetag` within a media_type
       - The last matching `behavioral_whitetag` within a media_type has
       - Normal whitetags
       - The first matching `behavioral_blacktag` within a media_type
       - The second matching `behavioral_blacktag` within a media_type
       - etc...
       - The second to last matching `behavioral_blacktag` within a media_type
       - The last matching `behavioral_blacktag` within a media_type
       - Normal blacktags have the lowest priority
- Each `behavioral_tag` can be individually configured to have (or not have [default]) a higher priority than favorites
   - This will move the specific tags to the highest priority
- If a matching `behavioral_tag` is not defined, the normal blacktag/whitetag `behavioral_statement` is used.
