### ISSUE TITLE
Limit The Number Of Characters Printed To Console And Saved To File

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#125]
- Came across an episode with a 93,000,000 character long title.
- When MUMC tried to print and/or write the title it hung for several minutes.
- Obviously, an episode title that long is not normal.
- But in the event it happens again, MUMC should gracefully handle this.

Add functionality to break up long strings in to smaller strings the `print()` function, `write()` function, and the OS can more quickly handle using the following configuration variables. See [output_controls](https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-admin_settings-output_controls) for additional information.

```yaml
  output_controls:
    character_limit:
      print: 128
      write: 128
```
