### ISSUE TITLE
Update Layout For Global And Media_Type Specific Tags

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#127]
### Global Tag Location

```yaml
advanced_settings:
  whitetags: [global,whitetags,go,here]
  blacktags: [global,blacktags,go,here]
```

### Media Specific Tag Location

```yaml
advanced_settings:
  behavioral_statements:
    movie:
      whitetagged:
        tags: [movie,specific,whitetags,go,here]
      blacktagged:
        tags: [movie,specific,blacktags,go,here]
    episode:
      whitetagged:
        tags: [series,season,episode,specific,whitetags,go,here]
      blacktagged:
        tags: [series,season,episode,specific,blacktags,go,here]
    audio:
      whitetagged:
        tags: [etc...]
      blacktagged:
        tags: [etc...]
    audiobook:
      whitetagged:
        tags: [etc...]
      blacktagged:
        tags: [etc...]
```

## Future tag layout

```yaml
advanced_settings:
  whitetags:
    global: [global,whitetags,go,here]
    movie: [movie,specific,whitetags,go,here]
    episode: [series,season,episode,specific,whitetags,go,here]
    audio: [etc...]
    audiobook: [etc...]
  blacktags:
    global: [global,blacktags,go,here]
    movie: [movie,specific,blacktags,go,here]
    episode: [series,season,episode,specific,blacktags,go,here]
    audio: [etc...]
    audiobook: [etc...]
```
