### ISSUE TITLE
episode_control not working

### ISSUE THREAD

**Issue by jm1tchell** [terrelsa13/media_cleaner#130]
### Have You Read The Wiki?:

Yes

### Describe What You Are Trying To Accomplish:

I am trying to keep a minimum of 1 episode of each series so the "next up" feature in Jellyfin funcitons, as described in the wiki.

### Describe What Is Happening:

MUMC is ignoring the episode_control section of the config file.

### Any Additional Information You Think Will Be Useful:

Reading through the closed issues, it has been noted that shows without episode numbers (which MUMC reports as SxxE?? when doing it's thing) don't work with episode_control.  But it appears that having a single show with this issue breaks episode_control for the entire library?  Is there any way around this?

**Comment by terrelsa13** [comment]
Hey @jm1tchell 
You are correct episodes not correctly reporting their season + episode numbers do not play nicely with the minimum episode control.

I would first try going to the metadata editor for the episode showing SxxE?? and verifying the season + episode numbers for this episode are set correctly. If not; give them the correct values, save, then try re-running MUMC. Let me know if that does or does not help.

**Comment by jm1tchell** [comment]
Thanks for getting back to me @terrelsa13

I actually deleted the offending files, and made sure the new downloads include the season/episode IDs.  No change, it is still not appearing to respect the episode_control criteria.  I'm running in dry run mode, but I seem to remember when I first set MUMC up it gave a list of items to be deleted and a separate list items that would be deleted if it weren't for the episode_control criteria.

I've tried v5.8.36, v5.9.13-beta (both in Docker) and also v.5.8.36 in a VM and all behave the same.

I think I have set up the config file correctly (the new configurator does not include this section by default, so I had to copy it from my old configuration):


```
advanced_settings:
  REMOVE_FILES: false
  delete_empty_folders:
    episode:
      season: true
      series: false
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 1
    minimum_episodes_behavior: Max Played Min Unplayed

```
