### ISSUE TITLE
Add Sonarr API - Check If Series Has Ended

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#131]
### Describe What You Are Trying To Accomplish And Why:

Use Sonarr to check if series has ended.
If it has, delete any episodes being kept from...

```yaml
advanced_settings:
  episode_control:
    minimum_episodes: int
    minimum_played_episodes: int
```

### A Clear And Concise Description Of What You Want To Happen:

When a series ends (according to Sonarr; which uses TheTVDB) the remaining episode(s) will be deleted.

```yaml
advanced_settings:
  episode_control:
    minimum_episodes: int
    minimum_played_episodes: int
    series_ended:
      delete_episodes: bool
admin_settings:
  media_managers:
    sonarr:
      enabled: true
      url: http://localhost:8989
      api_key: abcdef01234567899876543210fedcba
```

### Any Additional Information You Think Will Be Useful:

- This opens the door for Radarr, Lidarr, and Readarr API integration.
- No plans to add sickbeard, couchpotato, nzbget, sabnzbd, or any non-arr.
- No plans to add prowlarr, bazarr, or any other arr.
