### ISSUE TITLE
Unmonitor Movies, Series, & Episodes In Radarr & Sonarr After Deletion

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#132]
### Describe What You Are Trying To Accomplish And Why:

Remove need to manually set "Unmonitor Deleted Movies/Episodes" in Radarr/Sonarr.

### A Clear And Concise Description Of What You Want To Happen:

After deleting a movie or episode also unmonitor the media_item from Radarr or Sonarr.

```yaml
advanced_settings:
  radarr:
    movie:
      unmonitor: true
  sonarr:
    series:
      unmonitor: true
    episode:
      unmonitor: true
admin_settings:
  media_managers:
    sonarr:
      enabled: true
      url: http://localhost:8989
      api_key: abcdef01234567899876543210fedcba
    radarr:
      enabled: true
      url: http://localhost:7878
      api_key: abcdef01234567899876543210fedcba
```

### Any Additional Information You Think Will Be Useful:

- This opens the door for other Lidarr, and Readarr API integration.
- No plans to add sickbeard, couchpotato, nzbget, sabnzbd, or any non-arr.
- No plans to add prowlarr, bazarr, or any other arr.
