### ISSUE TITLE
Option To Remove Movie Entries & Series Entries From Radarr & Sonarr After MUMC Deletion

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#133]
### Describe What You Are Trying To Accomplish And Why:

Remove movie/episode entry from Radarr/Sonarr after MUMC deletes files.

### A Clear And Concise Description Of What You Want To Happen:

After deleting a movie or episode also remove entry from Radarr/Sonarr.

```yaml
advanced_settings:
  radarr:
    movie:
      remove: false
  sonarr:
    series:
      remove: false
admin_settings:
  media_managers:
    sonarr:
      enabled: true
      url: http://localhost:8989
      api_key: abcdef01234567899876543210fedcba
    radarr:
      enabled: true
      url: http://localhost:7878
      api_key: abcdef01234567899876543210fedcba
```
This removes the entry from *arr. It does not delete the file; which MUMC should have already deleted.

### Any Additional Information You Think Will Be Useful:

- This opens the door for other Lidarr, and Readarr API integration.
- No plans to add sickbeard, couchpotato, nzbget, sabnzbd, or any non-arr.
- No plans to add prowlarr, bazarr, or any other arr.
