### ISSUE TITLE
init_getMedia - 5.10.4

### ISSUE THREAD

**Issue by MagnusL3D-code** [terrelsa13/media_cleaner#137]
### Describe The Problem You Are Having:

I've been running MUMC on my Synology NAS for years but recently it stopped working and I imagen my old install just got outdated, system updates etc. So I downloaded 5.10.4 and set it up. installed the new requirments etc. But when I am running it in console to test it (ssh to my nas) it gives this output. Back when the old install worked running it in console also worked.

### Relevant MUMC Console Output:

```shell
Traceback (most recent call last):
  File "./mumc.py", line 143, in <module>
    MUMC()
  File "./mumc.py", line 108, in MUMC
    cfg=init_getMedia(cfg)
  File "/volume1/Misc/MUMC_new/mumc_modules/mumc_get_media.py", line 1118, in init_getMedia
    movie_returns=get_mediaItems(the_dict,the_dict['movie_dict']['media_type'],user_info,movie_returns)
  File "/volume1/Misc/MUMC_new/mumc_modules/mumc_get_media.py", line 755, in get_mediaItems
    the_dict[var_dict['media_dict_str']]['media_data']|=var_dict['media_data']
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

### MUMC Configiration File:

```yaml
---
version: 5.10.4
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: -1
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
    episode:
      played:
        condition_days: 0
        count_equality: '>='
        count: 1
      created:
        condition_days: 0
        count_equality: '>='
        count: 1
        behavioral_control: true
advanced_settings:
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 0
    minimum_episodes_behavior: Max Played Min Unplayed
    series_ended:
      delete_episodes: false
  REMOVE_FILES: false
admin_settings:
  server:
    brand: emby
    url: http://localhost:8096/emby
    auth_key: 492a9c26e7d24d248312eb216ae4cb9c
    admin_id: a5d38b108eba40a79ccf2d2715364b66
  users:
  - user_id: a5d38b108eba40a79ccf2d2715364b66
    user_name: theUser
    whitelist:
    - lib_id: 6c2a057148b4d7c20a207c789aba6d07
      collection_type: tvshows
      path: /volume1/Media Library/TV Shows
      network_path: null
      subfolder_id: '3'
      lib_enabled: true
    blacklist:
    - lib_id: 29391378c4118b35b77f84980d25f0a6
      collection_type: tvshows
      path: /volume1/Media Library/Anime Shows
      network_path: null
      subfolder_id: '5891'
      lib_enabled: true
    - lib_id: abebc196cc1b8bbf6f8bb5ca7b5ad6f1
      collection_type: movies
      path: /volume1/Media Library/Anime Movies
      network_path: null
      subfolder_id: '6184'
      lib_enabled: true
    - lib_id: bae808a3171745b993f53cd8d6ea8b82
      collection_type: tvshows
      path: /volume1/Media Library/TV Save
      network_path: null
      subfolder_id: '14252'
      lib_enabled: true
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /volume1/Media Library/Movies
      network_path: null
      subfolder_id: '5'
      lib_enabled: true
DEBUG: 0
...
```

### MUMC Version:

5.10.4

### What Platform(s) Does This Occur On?:

Linux

### Any Additional Information You Think Will Be Useful:

```shell

```
