### ISSUE TITLE
Returning 0 results

### ISSUE THREAD

**Issue by R3CKL3Z** [terrelsa13/media_cleaner#140]
### Have You Read The Wiki?:

Yes

### Describe What You Are Trying To Accomplish:

I want to remove movies older than 365 days and 0 times played.

In the settings, I changed the auth key to an API key because I got errors.

### Describe What Is Happening:

Empty list

### Any Additional Information You Think Will Be Useful:

Only got the executing logs

[return ifno.txt](https://github.com/user-attachments/files/19510662/return.ifno.txt)
[Settings message.txt](https://github.com/user-attachments/files/19510663/Settings.message.txt)

**Comment by terrelsa13** [comment]
Hi @R3CKL3Z 

I see you have multiple users. Because there was no mention of how the play count of individual users should be considered; I have made the following assumptions:
1. A `movie` will be `delete` when...
2. `all` users with the `movie` library `whitelisted`...
3. have a play `count` `==` to `0` for the `movie`...
4. and the `movie` was `created` `365` or more days ago

Please drill-down into:
- [filter_statements (advanced)](https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-advanced_settings-filter_statements)
- [behavioral_statements](https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-advanced_settings-behavioral_statements)

Then take a look at the same sections in the [full_configuration_file_example](https://github.com/terrelsa13/MUMC/wiki/Configuration_File_Examples-Full_Configuration_File_Example). Any configuration values missing from your `mumc_config.yaml` will assume the default values shown here.

-----------------
You will want to change the default values.

Add this to the `advanced_settings:` section of your `mumc_config.yaml`.

```yaml
advanced_settings:
  filter_statements:
    movie:
      query_filter:
        whitelisted:
          played: true
```

-----------------

Add this to the `advanced_settings:` section of your `mumc_config.yaml`.

```yaml
advanced_settings:
  behavioral_statements:
    movie:
      whitelisted:
        action: delete
        user_conditional: all
        played_conditional: all_created
        action_control: 3
        dynamic_behavior: true
```

-----------------

For further information on advanced `filter_statements` and `behavioral_statements` please read the following sections of the wiki:

- [Advanced filter_statement examples](https://github.com/terrelsa13/MUMC/wiki/Advanced_Filter_Statement_Examples)
- [Behavioral statement breakdown](https://github.com/terrelsa13/MUMC/wiki/Behavioral-Statement-Breakdown)
- [Advanced behavioral_statement examples](https://github.com/terrelsa13/MUMC/wiki/Advanced_Behavioral_Statement_Examples)
