### ISSUE TITLE
no data retrieved from the "get_info_for_movie_with_tmdbid: 758677"

### ISSUE THREAD

**Issue by niekcandaele** [terrelsa13/media_cleaner#141]
### Describe The Problem You Are Having:

There's a movie in my server with a TMDB id that (seemingly?) does not exist. I have tried manually finding this movie on https://www.themoviedb.org/ but no results. I'm not sure which file this is exactly in my server (if there's a way to search Jellyfin by tmdb ID, I didn't find it :( ). 

I believe that if MUMC encounters a scenario like this, it should not crash and instead gracefully handle the error (eg reporting that "cannot find info for file unknown_movie.mkv"). Then it should continue with the rest of the results

Disclaimer: this is my first time running MUMC. Maybe I'm doing something wrong?

Thank you!

### Relevant MUMC Console Output:

```shell
Cut out a whole bunch of noise from MUMC doing the scan, this is the final part of the output where the error occurs.

mumc  | 
mumc  | MOVIE POST PROCESSING STARTED...
mumc  | 
mumc  | PROCESSING BLACKLISTED MOVIES...
mumc  | 
mumc  | PROCESSING WHITELISTED MOVIES...
mumc  | 
mumc  | PROCESSING BLACKTAGGED MOVIES...
mumc  | 
mumc  | PROCESSING WHITETAGGED MOVIES...
mumc  | 
mumc  | PROCESSING FAVORITED MOVIES...
mumc  | 
mumc  | MOVIE POST PROCESSING COMPLETE.
mumc  | 
mumc  | ----------------------------------------------------------------------------------------
mumc  | Summary Of Deleted Media:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Dry Run Mode
mumc  | * advanced_settings > REMOVE_FILES: false
mumc  | * No Media Deleted
mumc  | * Items = 6
mumc  | ----------------------------------------------------------------------------------------
mumc  | To delete media, open /usr/src/app/config/mumc_config.yaml in a text editor:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Set advanced_settings > REMOVE_FILES: true
mumc  | ----------------------------------------------------------------------------------------
mumc  | 
mumc  | An error occured, a maximum of 4 attempts met, and no data retrieved from the "get_info_for_movie_with_tmdbid: 758677" lookup.
mumc  | 
mumc  |   URL: <urllib.request.Request object at 0x7f567a8965d0>
mumc exited with code 0
```

### MUMC Configiration File:

```yaml
version: 5.10.4
basic_settings:
  filter_statements:
    movie:
      created:
        condition_days: 365
        count_equality: '=='
        count: 0
        behavioral_control: true
advanced_settings:
  filter_statements:
    movie:
      query_filter:
        whitelisted:
          played: true
  behavioral_statements:
    movie:
      whitelisted:
        action: delete
        user_conditional: all
        played_conditional: all_created
        action_control: 3
        dynamic_behavior: true
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 0
    minimum_episodes_behavior: Max Played Min Unplayed
    series_ended:
      delete_episodes: false
  REMOVE_FILES: false
admin_settings:
  server:
    brand: jellyfin
    url: https://jellyfin.example.com:443
    auth_key: xxx
    admin_id: xxx
  behavior:
    list: whitelist
  users:
  - user_id: cb382569f8c2407f9d7611286210a543
    user_name: Arne
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 55847f5c1dc94fef9ea6004632765e3a
    user_name: Bientje
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 700d18dbb6004e4ebf00d6aa01f76526
    user_name: cata
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 6fcd4f003b10436a82e9917ab413d746
    user_name: catalysm
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: c5e24aedd328425684b7d23f97381a12
    user_name: danny
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: b4651193f0de4e2d989f8208614062ca
    user_name: emiel
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 9d7e0a097b7144818f8d7f83829b7aad
    user_name: Fien
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: a347f1e1c3e5455cb316c715bd4892a1
    user_name: Graever
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 931860f8352a4a87a89c7e05d1a74262
    user_name: inesdewitte
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 566e663dd0d34515950acc8ba542248b
    user_name: JamieKG
    whitelist: []
    blacklist: []
  - user_id: 3f3114347bb846dda5ff290bf67daef4
    user_name: Laurens
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: d786e19659af41228cbbc854e2e4892b
    user_name: Limon
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 66d000bddccc4b4d88b9a2d0a6409e5e
    user_name: maxim
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: f02f0c1488ff468e99f0e56a254d075e
    user_name: Mol
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: f8bf708008a743b5af2f31156f3329f6
    user_name: Osiris
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 1b1b922f621a42c2a6ab44fcb09596a7
    user_name: rcklz
    whitelist:
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /media/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 767bffe4f11c93ef34b805451a696a4e
      collection_type: tvshows
      path: /media/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 2bb9107eb4364cedbc454984b8a24451
    user_name: Sara
    whitelist: []
    blacklist:
    - lib_id: 23713f5a1661b305d18bf9a3baa5d36b
      collection_type: books
      path: /media/ebooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: c0c1444b416777d3fa55d5f13da1ce58
      collection_type: books
      path: /media/audiobooks
      network_path: null
      subfolder_id: null
      lib_enabled: true
  - user_id: 78584ef79e094e7cac62c78e4c266c52
    user_name: Thorgal
    whitelist: []
    blacklist: []
  media_managers:
    radarr:
      enabled: true
      url: https://radarr.example.com:443
      api_key: xxx
DEBUG: 0
```

### MUMC Version:

5.10.4

### What Platform(s) Does This Occur On?:

Docker

### Any Additional Information You Think Will Be Useful:

```shell

```

**Comment by terrelsa13** [comment]
Hi @niekcandaele 
This is a purposeful exit from MUMC. But I do understand your request.

As a personal preference; I purposely chose to not print an error and instead chose to exit MUMC. I did this because this is a newer feature and I want to know when something like this happens. Had MUMC continued with the "non-existing" tmdb id, someone else would have submitted this issue/bug say something like, "_movie-xyz is not being unmonitored (or removed) from Radarr even though it was deleted_". That would muddy the waters to understanding the root cause of the issue/bug. Because I am doing this in my free time I'd rather make it obvious where/why this failed.

Ok, with that out of the way. I would like to understand how a non-existing tmdb id was populated in the first place.

-----------------

- Emby/Jellyfin provide the tmdb id to MUMC.
- If the id does not exist, I would expect this movie to have issues populating metadata (title, images, descriptions, etc...) in Emby/Jellyfin.
- After MUMC gets the tmdb id from Emby/Jellyfin. MUMC uses it to query Radarr.
- I can see id `758677` does not appear to exist in TMDB
   - Going to `https://www.themoviedb.org/movie/758677` does however resolve to...
   - `https://www.themoviedb.org/movie/758677-coma`; however this is a blank page
   - When searching for **Coma** in TMDB; +300 movies are returned with that title
- Hopefully you have a movie in your library called **Coma**
   - If you do it will make the next part easier for both of us

-----------------
If you know the movie causing the issue...

#### Please do the following:
1. Login to Radarr using the admin user account
2. Select "movies"
3. Select the movie causing this issue
4. Select the 3-vertical-dots
5. Select "Edit Metadata"
6. Scroll to the "External IDs" section
7. Take a screenshot of the complete section
   1. Include all text boxes in the "External IDs" section
8. Reply with attached image.

-----------------
If you do not know the movie causing the issue...

#### Please do the following:
1. Open the `mumc_config.yaml`
2. Set `DEBUG: 4`
3. Run MUMC again
4. After the MUMC has exited due to the non-existing tmdb id
5. Go to the `mumc_config.yaml`
6. There will be a `mumc_DEBUG.log` file
7. Reply with the attached `mumc_DEBUG.log` file

**Comment by terrelsa13** [comment]
Please update to [v5.10.5](https://github.com/terrelsa13/MUMC/releases).
I have added additional output text to URL timeouts in this version.

**Comment by niekcandaele** [comment]
Thank you so much for the detailed response. I really appreciate you taking the time to thoroughly look at this. 😍 

I've found the offending movie in Jellyfin now ([IMDB link](https://www.imdb.com/title/tt6087226/)) :
![Image](https://github.com/user-attachments/assets/90dd927b-9e72-4ee8-ad5f-6a44581c0679)

I assumed that the request erroring was going to TMDB but with the new version, I see that I was mistaken! It's requesting data from Radarr. The movie is not monitored in Radarr (anymore? We don't manually download stuff so this definitely was monitored at some point). I'm checking with the person that does media management to see if he knows (I'm just the tech guy 😅).

This is probably a weird case then. What should MUMC do with a movie that's in Jellyfin, fits the deletion filters but is not monitored with Radarr?

As a person who still needs to run MUMC successfully for the first time ( 😉 ), I would expect MUMC to report the error and then move on to the next items. Not touching the file to be on the safe side.

For this specific case though, I would be OK just manually deleting this file too. I wont just yet in case you'd like me to run some more diagnostics or tests. I'm semi-worried that the other 5 movies that MUMC has flagged will have the same issue though.

```
mumc  | ----------------------------------------------------------------------------------------
mumc  | Summary Of Deleted Media:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Dry Run Mode
mumc  | * advanced_settings > REMOVE_FILES: false
mumc  | * No Media Deleted
mumc  | * Items = 6
mumc  | ----------------------------------------------------------------------------------------
mumc  | To delete media, open /usr/src/app/config/mumc_config.yaml in a text editor:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Set advanced_settings > REMOVE_FILES: true
mumc  | ----------------------------------------------------------------------------------------
mumc  | 
mumc  | An error occured, a maximum of 4 attempts met, and no data retrieved from the "get_info_for_movie_with_tmdbid: 758677" lookup.
mumc  |   Object: <bound method Request.header_items of <urllib.request.Request object at 0x7fbc9e57d3d0>>
mumc  |      URL: https://radarr.example.com:443/api/v3/movie?tmdbId=758677
mumc  |   Method: GET
mumc  |   Header: {'Accept': 'application/json', 'X-api-key': 'xxx', 'Content-type': 'application/json'}
mumc  |     Data: None
mumc exited with code 0
```


Again, thank you!

**Comment by terrelsa13** [comment]
> Thank you so much for the detailed response. I really appreciate you taking the time to thoroughly look at this.

Np!

> I've found the offending movie in Jellyfin now ([IMDB link](https://www.imdb.com/title/tt6087226/))
Good. Glad we were able to find it.

I am going to try to reproduce this on my end.

Here are the steps I am going to take. Let me know if this does not align with what you were saying above:

1. Find a movie in Emby/Jellyfin and Radarr
2. Remove the movie from Radarr
4. Run MUMC

Once I reproduce I will have a better direction on how MUMC will handle this.

> This is probably a weird case then. What should MUMC do with a movie that's in Jellyfin, fits the deletion filters but is not monitored with Radarr?

Now that I have a better understanding of what is happening. I agree with you. If MUMC comes across a media_item that radarr/sonarr are unable to return information; the un-monitor/delete from radarr/sonarr should be skipped and MUMC should continue to the next media_item. But let me reproduce this on my end, before I commit to making this change.

> For this specific case though, I would be OK just manually deleting this file too. I wont just yet in case you'd like me to run some more diagnostics or tests. I'm semi-worried that the other 5 movies that MUMC has flagged will have the same issue though.

Don't manually delete the movie(s) yet. Let me reproduce the issue first. Once I know I can reproduce this. I will let you know, then you can manually delete those movie(s) and keep moving toward your goal of getting MUMC to successfully run for the first time.

**Comment by terrelsa13** [comment]
I cannot get into a situation where a movie in Emby/Jellyfin but not in Radarr causes me to exceed the maximum number of retries.

On my setup when the movie does not exist in Radarr; Radarr returns a blank list `[]`.

This leads me to believe there is something going on with either Emby/Jellyfin or Radarr on your end.

- I am making the assumption you are removing the `url:` and `api_key:` information when sharing?
- I have no way to confirm if this is edited or what is actually in your `mumc_config.yaml`.
- To make sure there is no confusion; these `url:` and `api_key:` values will not work unless you have explicitly setup a local domain called `example.com` and you have manually changed Radarr to use an API key with the value `xxx`.
```yaml
  media_managers:
    radarr:
      enabled: true
      url: https://radarr.example.com:443
      api_key: xxx
```

Please confirm the `media_managers:` section has the correct information for Radarr in your `mumc_config.yaml`.
Below is an example.
```yaml
  media_managers:
    radarr:
      enabled: true
      url: http://192.168.1.23:7878 (or http://yourdomain.xyz)
      api_key: theAPIkeyFromRadarr0123456789abc
```

--------------------------------

Once you have confirmed the above is correct. Please use a computer that has access to Radarr, open a browser, and copy/paste the following URLs.

Can Radarr be accessed using the value in `url`?
```
https://radarr.example.com:443
```

Does Radarr return information about itself?
```
https://radarr.example.com:443/api/v3/system/status?apikey=xxx
```

Does this return an empty list `[]` in chrome/blank page in Firefox or does it timeout?
```
https://radarr.example.com:443/api/v3/movie?tmdbId=758677&apikey=xxx
```
This last one is the most important.

**Comment by terrelsa13** [comment]
Please update to [v5.10.6](https://github.com/terrelsa13/MUMC/releases).
When a media_item is missing from Radarr/Sonarr MUMC will ignore any Radar/Sonarr related actions for that media_item.

**Comment by niekcandaele** [comment]
Hiya, sorry for the delayed response, was traveling for work...

I've updated to 5.10.8 now.

> I am making the assumption you are removing the url: and api_key: information when sharing?

That assumption is correct, I censored the domain and api key before pasting here as our instance is available on the internet (with auth in between)

About the API responses you asked for, they return what you expect. The system/status call returns information and a call for the movie with tmbd returns a empty array. HOWEVER, I made an error! Since we have auth (Authelia) in between radarr, the raw api requests sent directly to our domain fail (as mumc of course cannot know about our auth layer).

I refactored our setup now. I added config so that Radarr and MUMC are in the same docker network. This now allows me to configure MUMC like this (note direct container hostname now, not external domain)

```yaml
  media_managers:
    radarr:
      enabled: true
      url: http://radarr:7878
      api_key: xxx
```

This is my latest output now. No more timeout:

```
mumc  | ----------------------------------------------------------------------------------------
mumc  | Summary Of Deleted Media:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Dry Run Mode
mumc  | * advanced_settings > REMOVE_FILES: false
mumc  | * No Media Deleted
mumc  | * Items = 6
mumc  | ----------------------------------------------------------------------------------------
mumc  | To delete media, open /usr/src/app/config/mumc_config.yaml in a text editor:
mumc  | ----------------------------------------------------------------------------------------
mumc  | * Set advanced_settings > REMOVE_FILES: true
mumc  | ----------------------------------------------------------------------------------------
mumc  | RadarrTMDBIdError: JellyfinMovieId: 4fb7a3c16bbb84d3cce7357d783f3e98 - MovieName: "Coma" does not exist in Radarr. Cannot be unmonitored.
mumc  | [DELETED]     Movie - Coma - 4fb7a3c16bbb84d3cce7357d783f3e98
mumc  | Traceback (most recent call last):
mumc  |   File "/usr/src/app/./mumc.py", line 143, in <module>
mumc  |     MUMC()
mumc  |   File "/usr/src/app/./mumc.py", line 117, in MUMC
mumc  |     print_and_delete_items(deleteItems,cfg)
mumc  |   File "/usr/src/app/mumc_modules/mumc_delete.py", line 142, in print_and_delete_items
mumc  |     media_item_data=get_MOVIE_radarrInfo(item['mumc']['providerIds']['Tmdb'],the_dict)
mumc  |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
mumc  | KeyError: 'Tmdb'
```
