### ISSUE TITLE
Error in reporting to be deleted files

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#142]
### Describe The Problem You Are Having:

Hi,

About to switch from Emby -> Jellyfin. Now configuring your amazing script and running both parallel until the results are the same.

I run into an reporting issue with Jellyfin. The overview in the log file comes with an error.
 

### Relevant MUMC Console Output:

```shell
----------------------------------------------------------------------------------------
Summary Of Deleted Media:
----------------------------------------------------------------------------------------
* Dry Run Mode
* advanced_settings > REMOVE_FILES: false
* No Media Deleted
* Items = 10
----------------------------------------------------------------------------------------
To delete media, open /home/patrick/docker-config/jellyfin/MUMC/mumc_config.yaml in a text editor:
----------------------------------------------------------------------------------------
* Set advanced_settings > REMOVE_FILES: true
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/patrick/docker-config/jellyfin/MUMC/mumc.py", line 143, in <module>
    MUMC()
  File "/home/patrick/docker-config/jellyfin/MUMC/mumc.py", line 117, in MUMC
    print_and_delete_items(deleteItems,cfg)
  File "/home/patrick/docker-config/jellyfin/MUMC/mumc_modules/mumc_delete.py", line 125, in print_and_delete_items
    media_item_data=get_MOVIE_radarrInfo(item['mumc']['providerIds']['Tmdb'],the_dict)
  File "/home/patrick/docker-config/jellyfin/MUMC/mumc_modules/mumc_item_info.py", line 71, in get_MOVIE_radarrInfo
    url=the_dict['admin_settings']['media_managers']['radarr']['url'] + '/api/v3/movie?tmdbId=' + str(radarrTMdbId)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### MUMC Configiration File:

```yaml
---
version: 5.10.4
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: 14
        count_equality: '>='
        count: 1
      created:
        condition_days: 730
        count_equality: '>='
        count: 0
        behavioral_control: true
    episode:
      played:
        condition_days: 14
        count_equality: '>='
        count: 1
      created:
        condition_days: 730
        count_equality: '>='
        count: 0
        behavioral_control: true
advanced_settings:
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 0
    minimum_episodes_behavior: Max Played Min Unplayed
    series_ended:
      delete_episodes: false
  console_controls:
    headers:
      script:
        show: true
      summary:
        show: true
      user:
        show: false
    footers:
      script:
        show: false
    movie:
      delete:
        show: true
        formatting:
          font:
            color: 'red'
      keep:
        show: false
      post_processing:
        show: false
      summary:
        show: true
    episode:
      delete:
        show: true
      keep:
        show: false
      post_processing:
        show: false
      summary:
        show: true
    warnings:
      script:
        show: true
  REMOVE_FILES: false
admin_settings:
  server:
    brand: jellyfin
    url: http://localhost:8097
    auth_key: 82b545c24f6144fa9ef831ad998d16e8
    admin_id: 25c9ad11672f4489bfc06e6f0d5d6329
  users:
  - user_id: 5b8d6ac240dc4b858a7d2f14f0c2dd7b
    user_name: Patrick
    whitelist: []
    blacklist:
    - lib_id: 3bfa1069126e8cc3a0f038cf12196583
      collection_type: movies
      path: /data/moviesuhd
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 5ddaa59a73205234890fdcfc683e14ed
      collection_type: tvshows
      path: /data/tvshows
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /data/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
DEBUG: 0
...
```

### MUMC Version:

5.10.4

### What Platform(s) Does This Occur On?:

Linux

### Any Additional Information You Think Will Be Useful:

```shell
MUMC Version: 5.10.4
MUMC Config Version: 5.10.4
MUMC Config Path: /home/patrick/docker-config/jellyfin/MUMC/mumc_config.yaml
Jellyfin Version: 10.10.6
Python Version: 3.9.2
OS Info: Linux-5.10.0-34-amd64-x86_64-with-glibc2.31
```
