### ISSUE TITLE
unrelated character in log output

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#143]
### Describe The Problem You Are Having:

I have mentioned 3 things. I can make different bug report. Please let me know.

1.  There are unrelated characters in the logfile. Notepad++ seems to define it as a ESC character. It only appears to be at movies in my setup. In the screen output there are no ESC characters

2. I have also played with color for movies but in my screen output is does not color the whole line as (in my case) RED. Just a part is RED.

![Image](https://github.com/user-attachments/assets/e52efcf6-aaa3-4dbc-8db8-7b8b87e81323)

3. Another thing is that I would expect this file to be deleted in my setup. But it is not in the summary. Only played media. So it looks like its AND where I expect it to be OR in the filter_statements. Maybe episode_control. I'm not seeing it 

```
:*[DELETE] - Episode - Blade Runner: Black Lotus - s01.e10 - Clair De Lune - Adult Swim - Unplayed - Play Count: 0 - Created 1084 days ago - Favorite: False - Whitetag: False - Blacktag: False - Whitelisted: False - Blacklisted: True - EpisodeID: aa595d9d51504a50f5836d577af860f3
```

### Relevant MUMC Console Output:

This is from the LOG file
```shell
[31m:*[DELETE] - Movie - The Professional - Cerito Films - Unplayed - Play Count: 0 - Created 1153 days ago - Favorite: False - Whit[0metag: False - Blacktag: False - Whitelisted: False - Blacklisted: True - MovieID: c423775cf37546ce4daec9a3f6b007f0
```

### MUMC Configiration File:

```yaml
---
version: 5.10.4
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: 14
        count_equality: '>='
        count: 1
      created:
        condition_days: 730
        count_equality: '>='
        count: 0
        behavioral_control: true
    episode:
      played:
        condition_days: 14
        count_equality: '>='
        count: 1
      created:
        condition_days: 730
        count_equality: '>='
        count: 0
        behavioral_control: true
advanced_settings:
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 0
    minimum_episodes_behavior: Max Played Min Unplayed
    series_ended:
      delete_episodes: false
  console_controls:
    headers:
      script:
        show: true
      summary:
        show: true
      user:
        show: false
    footers:
      script:
        show: false
    movie:
      delete:
        show: true
        formatting:
          font:
            color: 'red'
      keep:
        show: false
      post_processing:
        show: false
      summary:
        show: true
    episode:
      delete:
        show: true
      keep:
        show: false
      post_processing:
        show: false
      summary:
        show: true
    warnings:
      script:
        show: true
  REMOVE_FILES: false
admin_settings:
  server:
    brand: jellyfin
    url: http://localhost:8097
    auth_key: 82b545c24f6144fa9ef831ad998d16e8
    admin_id: 25c9ad11672f4489bfc06e6f0d5d6329
  users:
  - user_id: 5b8d6ac240dc4b858a7d2f14f0c2dd7b
    user_name: Patrick
    whitelist: []
    blacklist:
    - lib_id: 3bfa1069126e8cc3a0f038cf12196583
      collection_type: movies
      path: /data/moviesuhd
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 5ddaa59a73205234890fdcfc683e14ed
      collection_type: tvshows
      path: /data/tvshows
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: f137a2dd21bbc1b99aa5c0f6bf02a805
      collection_type: movies
      path: /data/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
DEBUG: 0
...
```

### MUMC Version:

5.10.7

### What Platform(s) Does This Occur On?:

Linux

### Any Additional Information You Think Will Be Useful:

```shell
----------------------------------------------------------------------------------------
Time Stamp Start: 20250405110632
----------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------
MUMC Version: 5.10.7
MUMC Config Version: 5.10.4
MUMC Config Path: /home/patrick/docker-config/jellyfin/MUMC/mumc_config.yaml
Jellyfin Version: 10.10.6
Python Version: 3.9.2
OS Info: Linux-5.10.0-34-amd64-x86_64-with-glibc2.31
----------------------------------------------------------------------------------------
```

**Comment by keppo070** [comment]
I'm thinking that the ESC is related to my COLOR use. The logfile is TEXT and the COLOR is probably making its way in the LOG file

**Comment by terrelsa13** [comment]
## Issue 2  
> 2. I have also played with color for movies but in my screen output is does not color the whole line as (in my case) RED. Just a part is RED.

I have fixed the color issue in the latest release [v5.10.8](https://github.com/terrelsa13/MUMC/releases). I was only formatting up to the the number of characters defined in `output_controls` > `character_limit` > `print` or in your case, the default value of the first `128` characters. After the first 128 characters or what is defined in `output_controls` > `character_limit` > `print`; the remaining characters where unformatted.

```yaml
admin_settings:
  output_controls:
    character_limit:
      print: 128
```

This is what was being sent to the Python print() function in v5.10.7

```
'\x1b[31m:*[DELETE] - Episode - Blade Runner: Black Lotus - s01.e10 - Clair De Lune - Adult Swim - Unplayed - Play Count: 0 - Created 10\x1b[0m'
'84 days ago - Favorite: False - Whitetag: False - Blacktag: False - Whitelisted: False - Blacklisted: True - EpisodeID: aa595d9'
'd51504a50f5836d577af860f3'
'\n'
```

This is what is being sent to the Python print() function in v5.10.8

```
'\x1b[31m:*[DELETE] - Episode - Blade Runner: Black Lotus - s01.e10 - Clair De Lune - Adult Swim - Unplayed - Play Count: 0 - Created 10\x1b[0m'
'\x1b[31m84 days ago - Favorite: False - Whitetag: False - Blacktag: False - Whitelisted: False - Blacklisted: True - EpisodeID: aa595d9\x1b[0m'
'\x1b[31md51504a50f5836d577af860f3\x1b[0m'
'\x1b[0m\n'
```

## Issue 1

> 1. There are unrelated characters in the logfile. Notepad++ seems to define it as a ESC character. It only appears to be at movies in my setup. In the screen output there are no ESC characters

I was not able to reproduce this on my end.
But you are correct, somehow the formatting for the console output is getting put into to `mumc_DEBUG.log`.

## Issue 3

> 3. Another thing is that I would expect this file to be deleted in my setup. But it is not in the summary. Only played media. So it looks like its AND where I expect it to be OR in the filter_statements. Maybe episode_control. I'm not seeing it 

MUMC is working correctly. There are a couple ways you can get the episode to delete. You will have to decide which is the right way for your setup.

### Option 1: (The Hammer - Most likely to be used when monitoring a single user)

When `behavioral_control : true` during post processing any `media_items` found meeting the criteria for `filter_statements` > `episode` > `created` will also have to meet the criteria for `filter_statements` > `episode` > `played` before it can be deleted.

When `behavioral_control : false` during post processing any `media_items` found meeting the criteria for `filter_statements` > `episode` > `created` will NOT have to meet the criteria for `filter_statements` > `episode` > `played` and will be deleted.

For more information drill down into the wiki about **basic** [`filter_statements`](https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-basic_settings-filter_statements-media_type).

Update your config file to use this value.

```yaml
basic_settings:
  filter_statements:
    episode:
      created:
        behavioral_control: false
```

### Option 2: (The Scalpel - Most likely to be used when monitoring multiple users)

`behavioral_statements` allow fine tuning the conditions that must be met before a item is deleted or kept. For more information drill down into the wiki about [`behavioral_statements`](https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-advanced_settings-behavioral_statements-media_type).

I see you have a single user. I have made the following assumptions:

1. An `episode` will be `delete` when...
2. `all` users have the `tvshows` library `blacklisted`...
3. `all` users have a `play` `count` `==` to `0` for the `episode`...
4. and the `episode` was `created` `730` or more days ago

Add this to your config file.

```yaml
advainced_settings:
  behavioral_statements:
    episode:
      blacklisted:
        action: delete
        user_conditional: all
        played_conditional: all_created
        action_control: 3
        dynamic_behavior: false
```

Informational - `favorited`, `whitetagged`, `blacktagged`, `whitelisted`, and `blacklisted` all have their own `behavioral_statements` for each `media_type`.

### Option 1 OR Option 2 (not both)

There is no need to implement both options.
Choose the one option that works best for your setup.
