### ISSUE TITLE
Error When Deleting

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#154]
### Describe The Problem You Are Having:

`DELETE` method returns empty `b''` binary data. Need to instead return the value from `url.getcode()`.

### Relevant MUMC Console Output:

```shell
Traceback (most recent call last):
  File "/media/amunra/scripts/MUMC/mumc.py", line 172, in <module>
    MUMC()
  File "/media/amunra/scripts/MUMC/mumc.py", line 139, in MUMC
    print_and_delete_items(deleteItems,cfg)
  File "/media/amunra/scripts/MUMC/mumc_modules/mumc_delete.py", line 112, in print_and_delete_items
    if (delete_media_item(item['Id'],the_dict)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/amunra/scripts/MUMC/mumc_modules/mumc_delete.py", line 46, in delete_media_item
    if ((rtn >= 200) and (rtn < 300)):
         ^^^^^^^^^^
TypeError: '>=' not supported between instances of 'bytes' and 'int'
```

### MUMC Configiration File:

```yaml
---
version: 5.8.25-beta
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: 31
        count_equality: '>='
        count: 1
      created:
        condition_days: 0
        count_equality: '>='
        count: 0
        behavioral_control: true
    #episode:
      #played:
        #condition_days: 13
        #count_equality: '>='
        #count: 1
      #created:
        #condition_days: 1461
        #count_equality: '>='
        #count: 0
        #behavioral_control: true
advanced_settings:
  filter_statements:
    movie:
      query_filter:
        whitelisted:
          favorited: true
          whitetagged: true
          blacktagged: true
          played: true
        blacklisted:
          favorited: true
          whitetagged: true
          blacktagged: true
          played: true
    episode:
      query_filter:
        whitelisted:
          favorited: true
          whitetagged: true
          blacktagged: true
          played: true
        blacklisted:
          favorited: true
          whitetagged: true
          blacktagged: true
          played: true
  behavioral_statements:
    movie:
      favorited:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
        dynamic_behavior: false
        extra:
          genre: 0
          library_genre: 0
      whitelisted:
        action: keep
        user_conditional: all
        played_conditional: any_any
        action_control: 3
        dynamic_behavior: false
      blacklisted:
        action: delete
        user_conditional: any
        played_conditional: any_any
        action_control: 3
        dynamic_behavior: false
    episode:
      favorited:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
        dynamic_behavior: false
        extra:
          genre: 0
          season_genre: 0
          series_genre: 0
          library_genre: 0
          studio_network: 0
          studio_network_genre: 0
      whitelisted:
        action: keep
        user_conditional: all
        played_conditional: any_any
        action_control: 3
        dynamic_behavior: false
      blacklisted:
        action: delete
        user_conditional: any
        played_conditional: any_any
        action_control: 3
        dynamic_behavior: false
  delete_empty_folders:
    episode:
      season: true
      series: true
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 1
    minimum_episodes_behavior: Max Played Min Unplayed
    series_ended:
      delete_episodes: true
  radarr:
    movie:
      unmonitor: true
  sonarr:
    series:
      unmonitor: true
    episode:
      unmonitor: true
  trakt_fix:
    set_missing_last_played_date:
      audio: false
  console_controls:
    movie:
      delete:
        show: false
      keep:
        show: false
    episode:
      delete:
        show: false
      keep:
        show: false
    audio:
      delete:
        show: false
      keep:
        show: false
  UPDATE_CONFIG: false
  REMOVE_FILES: true
admin_settings:
  behavior:
    list: blacklist
    matching: byId
    users:
      monitor_disabled: true
  server:
    brand: emby
    url: https://emby.url.com
    auth_key: xxxx
    admin_id: xxxx
  users:
  - user_id: 4c03eed461624bb9bf8bcc5a4515e2ef
    user_name: Guest.User
    whitelist: []
    blacklist:
    - lib_id: 7c6b1294b30d4c722993e4036d0425ac
      collection_type: tvshows
      path: /media/pharaoh/xbmc/tv
      network_path: smb://xbmc14lxc.url.com/tv
      subfolder_id: '13426999'
      lib_enabled: true
    - lib_id: c8ca023cdbb96c78e4de5fcb477df512
      collection_type: movies
      path: /media/pharaoh/xbmc/movies
      network_path: smb://xbmc14lxc.url.com/movies
      subfolder_id: '13428270'
      lib_enabled: true
  - user_id: 97fbc9cf21724e4eb30bd2fb9268559d
    user_name: Terrel.User
    whitelist: []
    blacklist:
    - lib_id: 60c6bb241c9195d4b536e84e02b31783
      collection_type: music
      path: /media/pharaoh/xbmc/music/albums
      network_path: smb://xbmc14lxc.url.com/music/albums
      subfolder_id: '13400195'
      lib_enabled: false
    - lib_id: 7aa60e8e6d7f4760a5800c81d7dbd297
      collection_type: audiobooks
      path: /media/pharaoh/xbmc/audiobooks
      network_path: smb://xbmc14lxc.url.com/audiobook
      subfolder_id: '19397652'
      lib_enabled: false
    - lib_id: 7c6b1294b30d4c722993e4036d0425ac
      collection_type: tvshows
      path: /media/pharaoh/xbmc/tv
      network_path: smb://xbmc14lxc.url.com/tv
      subfolder_id: '13426999'
      lib_enabled: true
    - lib_id: c8ca023cdbb96c78e4de5fcb477df512
      collection_type: movies
      path: /media/pharaoh/xbmc/movies
      network_path: smb://xbmc14lxc.url.com/movies
      subfolder_id: '13428270'
      lib_enabled: true
  - user_id: 936055badcd3462aa4fa9cc1f6e42e7f
    user_name: LaLa.User
    whitelist: []
    blacklist: []
    #- lib_id: 7c6b1294b30d4c722993e4036d0425ac
      #collection_type: tvshows
      #path: /media/pharaoh/xbmc/tv
      #network_path: smb://xbmc14lxc.url.com/tv
      #subfolder_id: '13426999'
      #lib_enabled: true
    #- lib_id: c8ca023cdbb96c78e4de5fcb477df512
      #collection_type: movies
      #path: /media/pharaoh/xbmc/movies
      #network_path: smb://xbmc14lxc.url.com/movies
      #subfolder_id: '13428270'
      #lib_enabled: true
  media_managers:
    radarr:
      url: https://radarr.url.com
      api_key: xxxx
    sonarr:
      url: https://sonarr.url.com
      api_key: xxxx
  api_controls:
    attempts: 4
    item_limit: 25
  cache:
    size: 64
    fallback_behavior: LRU
    minimum_age: 200
DEBUG: 1
...
```

### MUMC Version:

v5.11.6-alpha and v5.11.6-beta and v5.10.11

### What Platform(s) Does This Occur On?:

Linux, Windows, Docker

### Any Additional Information You Think Will Be Useful:

```shell

```
