### ISSUE TITLE
Allow Multiple Instances Of Radarr and Sonarr

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#157]
### Describe What You Are Trying To Accomplish And Why:

> ...and final question is, can MUMC run/integrate with multiple Radarr/Sonarr instances? Say if you have one strictly for 4K and another for FullHD and lower?

 _Originally posted by @cmcooper1980 in [#155](https://github.com/terrelsa13/MUMC/issues/155#issuecomment-2884784310)_

### A Clear And Concise Description Of What You Want To Happen:

Change `admin_settings` > `media_managers` > `Radarr`/`Sonarr` to a list which allows multiple instances of Radarr/Sonarr.

Current `media_mangers` yaml structure:
```yaml
  media_managers:
    radarr:
      enabled: true
      url: https://radarr0.example.com
      api_key: 0bcdefabcdef01234567890123456789
    sonarr:
      enabled: true
      url: https://radarr0.example.com
      api_key: abcdefabcdef01234567890123456780
```

Proposed `media_managers` yaml structure:
```yaml
  media_managers:
    radarr:
    - enabled: true
      url: https://radarr0.example.com
      api_key: 0bcdefabcdef01234567890123456789
    - enabled: true
      url: https://radarr1.example.com
      api_key: 1bcdefabcdef01234567890123456789
    - enabled: true
      url: https://radarrX.example.com
      api_key: xbcdefabcdef01234567890123456789
    sonarr:
    - enabled: true
      url: https://sonarr0.example.com
      api_key: abcdefabcdef01234567890123456780
    - enabled: true
      url: https://sonarr1.example.com
      api_key: bcadefabcdef01234567890123456781
    - enabled: true
      url: https://sonarrX.example.com
      api_key: cabdefabcdef0123456789012345678x
```

### Describe Alternatives You Have Considered:

Leaving it as is.

### Any Additional Information You Think Will Be Useful:

Will need to convert any configs using the existing yaml structure into the proposed yaml structure.

**Comment by cmcooper1980** [comment]
So with the proposed change, will this work as is if I were to go into the mumc_config.yaml and change that section until the initial setup is revamped to prompt for mullti-radarr/sonarr instances? Or is there a bunch of backend stuff/references that you need to work on to enable this feature?

**Comment by terrelsa13** [comment]
Not yet. This feature request is just me explaining how I think this change is going to happen. I still need to make a bunch of changes to the MUMC code before it is able to handle multiple instances of radarr/sonarr.

**Comment by terrelsa13** [comment]
I have pushed the changes to allow multiple instance of Radarr/Sonarr to the `MUMC_alpha` branch. If you are interested in testing this out on your end and providing any feedback, you can try it by spinning up a Docker using `ghcr.io/terrelsa13/mumc:MUMC_alpha`.

**Comment by cmcooper1980** [comment]
Do I have to start from scratch with a new config or can I use the `CONFIG_UPDATER` to simply add additional radarr/sonarr instances?

**Comment by terrelsa13** [comment]
You will have to either manually add them. Or enable the config updater and use [command line arguments/environmental variables](https://github.com/terrelsa13/MUMC/wiki/Command-line-Arguments) to have MUMC add the entries. If using command line arguments/environmental variables you will want to put the current and new instances of Radarr/Sonarr URLs and API keys.

**Comment by cmcooper1980** [comment]
So I just tried spinning up the `MUMC_alpha` branch and immediately having errors.

Steps taken:
1. docker compose down to bring down working instance
2. created backup of my working `mumc_config.yaml` file then deleted the original
3. 'touch' new, blank `mumc_config.yaml` file
4.  updated my docker-compose.yml file to point to the new `MUMC_alpha` tag and ran `docker compose up` (non-daemon) to see the output which is below:

```
chris@atlantis:~/.docker/mumc$ cat ~/.config/appdata/mumc/config/mumc_config.yaml
chris@atlantis:~/.docker/mumc$ docker compose up
[+] Running 2/1
 ✔ Network mumc_default  Created                                                                                              0.1s
 ✔ Container mumc        Created                                                                                              0.0s
Attaching to mumc
mumc  | Traceback (most recent call last):
mumc  |   File "/usr/src/app/./mumc.py", line 172, in <module>
mumc  |     MUMC()
mumc  |   File "/usr/src/app/./mumc.py", line 39, in MUMC
mumc  |     cmdopt_dict['argv']=cfgCheckARGENV(argvCfgChecker)
mumc  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mumc  |   File "/usr/src/app/mumc_modules/mumc_argenv_check.py", line 121, in cfgCheckARGENV
mumc  |     if (not ((radarr_url:=argvCfgChecker.checkList('-radarr_url',value=None,instanceType=argvCfgChecker.list,required=False,minLength=len(argvCfgChecker.cfg['-radarr_api_key']),maxLength=len(argvCfgChecker.cfg['-radarr_api_key']),errOut=False)) == None)):
mumc  |                                                                                                                                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
mumc  | KeyError: '-radarr_api_key'
mumc exited with code 1
```

**Comment by terrelsa13** [comment]
Not at a computer, had to run errands.

But, try using both `radarr_url` and `radarr_api_key` together.

Looks like I need to check if this is the case, then gracefully handle when using one without the other.

**Comment by terrelsa13** [comment]
In compose it'll look like this: 

```yaml
version: '3.9'
services:
   mumc:
      container_name: 'mumc'
      image: ghcr.io/terrelsa13/mumc:alpha
      environment:
         .
         .
         .
         RADARR_URL: 'http://192.168.1.23:7878,http://192.168.1.23:8787'
         RADARR_API_KEY: 'abcdef01234567899876543210fedcba,xbcdef01234567899876543210fedcbx'
         .
         .
         .
```

If you are using both. I will have to look more deeply into this once I'm in front of a computer again.

**Comment by cmcooper1980** [comment]
So this is my `docker-compose.yml` file (minus the `version: '3.9'` up top since it's deprecated):

```
services:
   mumc:
      container_name: 'mumc'
#      image: ghcr.io/terrelsa13/mumc:latest
#      image: ghcr.io/terrelsa13/mumc:v5.10.12
      image: ghcr.io/terrelsa13/mumc:MUMC_alpha
#      image: ghcr.io/terrelsa13/mumc:MUMC_beta
      environment:
         TZ: 'America/Chicago' # change to your timezone; required
         BRAND: 'jellyfin' #or 'emby'
         URL: 'http://192.168.0.10:8097' #or 'https://example.domain.com' or htttp://192.168.1.234:8096/emby
         USERNAME: '${ADMIN_USERNAME}' #may be set to '' after MUMC creates the configuration file
         PASSWORD: '${ADMIN_PASSWORD}' #may be set to '' after MUMC creates the configuration file
         LIST_BEHAVIOR: 'blacklist' #or 'whitelist'
         MATCHING_BEHAVIOR: 'byId' #or 'byPath' or 'byNetworkPath'
         BLACKTAGS: '' #'blacktag1,blacktag 2,blacktag_3,blacktag-4'
         WHITETAGS: '' #'whitetag1,whitetag 2,whitetag_3,whitetag-4'
         MONITOR_DISABLED_USERS: true #or false
         USER_LIBRARY_SELECTION: 1 # or 2 or 1 or 0 (2, 1, and 0 require 'stdin_open: true' and 'tty: true')
         RADARR_URL: '${RADARR_URL},${RADARR2_URL}' #or 'https://example.domain.com' or https://192.168.1.234:7878/radarr
         RADARR_API_KEY: '${RADARR_API_KEY},${RADARR2_API_KEY}' #may be set to '' after MUMC creates the configuration file
#         SONARR_URL: '${SONARR_URL}' #or 'https://example.domain.com' or https://192.168.1.234:8989/sonarr
#         SONARR_API_KEY: '${SONARR_API_KEY}' #may be set to '' after MUMC creates the configuration file
      volumes:
         - '${DOCKER_VOLUME_CONFIG}/mumc/config/mumc_config.yaml:/usr/src/app/config/mumc_config.yaml' #specify the config file lo>
         - '${DOCKER_VOLUME_CONFIG}/mumc/logs/mumc_DEBUG.log:/usr/src/app/logs/mumc_DEBUG.log' #specify the debug log location on >
      stdin_open: true # docker run -i
      tty: true # docker run -t
```

I run `docker compose up` (non-daemon to see output) and I get this:

```
chris@atlantis:~/.docker/mumc$ docker compose up
[+] Running 2/1
 ✔ Network mumc_default  Created                                                                                              0.1s
 ✔ Container mumc        Created                                                                                              0.0s
Attaching to mumc
mumc  | Traceback (most recent call last):
mumc  |   File "/usr/src/app/./mumc.py", line 172, in <module>
mumc  |     MUMC()
mumc  |   File "/usr/src/app/./mumc.py", line 39, in MUMC
mumc  |     cmdopt_dict['argv']=cfgCheckARGENV(argvCfgChecker)
mumc  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mumc  |   File "/usr/src/app/mumc_modules/mumc_argenv_check.py", line 121, in cfgCheckARGENV
mumc  |     if (not ((radarr_url:=argvCfgChecker.checkList('-radarr_url',value=None,instanceType=argvCfgChecker.list,required=False,minLength=len(argvCfgChecker.cfg['-radarr_api_key']),maxLength=len(argvCfgChecker.cfg['-radarr_api_key']),errOut=False)) == None)):
mumc  |                                                                                                                                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
mumc  | KeyError: '-radarr_api_key'
mumc exited with code 1
```
The first time I shared the error was with just one instance of Radarr...the above is with your recommendation of entering both instances, comma delimited (just using `.env` file as opposed to explicitly entering the info in the compose).
