### ISSUE TITLE
Allow Each Instance Of Radarr/Sonarr To Have Independent Configuration Values

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#158]
### Describe What You Are Trying To Accomplish And Why:

Give each instance of Radarr/Sonarr the ability to behave differently.

### A Clear And Concise Description Of What You Want To Happen:

Current configuration options

```yaml
advanced_settings:
  radarr:
    movie:
      unmonitor: boolean
      remove: boolean
  sonarr:
    series:
      unmonitor: boolean
      remove: boolean
    episode:
      unmonitor: boolean
```

Proposed configuration optoins

```yaml
advanced_settings:
  radarr:
    movie:
    - unmonitor: boolean
      remove: boolean
    - unmonitor: boolean
      remove: boolean
    - unmonitor: boolean
      remove: boolean
  sonarr:
    series:
    - unmonitor: boolean
      remove: boolean
    - unmonitor: boolean
      remove: boolean
    - unmonitor: boolean
      remove: boolean
    episode:
    - unmonitor: boolean
    - unmonitor: boolean
    - unmonitor: boolean
```

### Describe Alternatives You Have Considered:

Leave it as is.

### Any Additional Information You Think Will Be Useful:

Will need to convert any configs using the existing yaml structure into the proposed yaml structure.
