### ISSUE TITLE
episode_control causing mumc to crash

### ISSUE THREAD

**Issue by jm1tchell** [terrelsa13/media_cleaner#161]
### Describe The Problem You Are Having:

This may be an edge case that is more properly an enhancement request rather than a bug.  

When a Jellyfin TV show library has no IMDB, etc. database entry for it's contents (eg. downloaded video podcasts that are organized as season/episode), MUMC will crash if episode_control is enabled.

If the above library is commented out in config.yaml, episode_control behaves as expected.
If minimum_episodes is set to 0 and minimum_played_episodes is commented out, MUMC behaves as expected.
if either minimum_episodes or minimum_played_episodes is set to 1, MUMC will crash as shown in the console output below.

### Relevant MUMC Console Output:

```shell
mumc  | PROCESSING FAVORITED EPISODES...
mumc  | 
mumc  | PROCESSING MINIMUM NUMBER EPISODES...
mumc  | Traceback (most recent call last):
mumc  |   File "/usr/src/app/./mumc.py", line 178, in <module>
mumc  |     MUMC()
mumc  |   File "/usr/src/app/./mumc.py", line 139, in MUMC
mumc  |     deleteItems_dict=init_postProcessing(cfg)
mumc  |                      ^^^^^^^^^^^^^^^^^^^^^^^^
mumc  |   File "/usr/src/app/mumc_modules/mumc_post_process.py", line 782, in init_postProcessing
mumc  |     deleteItems_dict=start_postProcessing(the_dict,episode_dict,deleteItems_dict)
mumc  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mumc  |   File "/usr/src/app/mumc_modules/mumc_post_process.py", line 728, in start_postProcessing
mumc  |     deleteItems_media=postProcessing(the_dict,media_dict)
mumc  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mumc  |   File "/usr/src/app/mumc_modules/mumc_post_process.py", line 689, in postProcessing
mumc  |     postproc_dict['minEpisodesToKeep'].trackEpisodes_byUserId()
mumc  |   File "/usr/src/app/mumc_modules/mumc_minimum_episodes.py", line 88, in trackEpisodes_byUserId
mumc  |     self.episodes_toBeDeletedOrRemain[episodeItem['SeriesId']]['IMdBId'] = self.episodeCounts_byUserId[userId][episodeItem['SeriesId']]['IMdBId']
mumc  |                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
mumc  | KeyError: 'IMdBId'
mumc exited with code 1
```

### MUMC Configiration File:

```yaml
---
version: 5.11.25-beta
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: 10
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
    episode:
      played:
        condition_days: 30
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
advanced_settings:
  REMOVE_FILES: false
  # REMOVE_FILES: true
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 1
    minimum_episodes_behavior: 'Max Played Min Unplayed'

admin_settings:
  server:
    brand: jellyfin
    url: <redacted>
    auth_key: <redacted>
    admin_id: <redacted>
  users:
  - user_id: 99667b8f3d654797a04f18d2f1baeec2
    user_name: jellyfin
    whitelist: []
    blacklist:
    - lib_id: 34f331a89ce405e2b877d68d5ee4d4a2
      lib_name: Podcasts
      collection_type: tvshows
      path: /media/pvr/podcasts
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 4bedcfbb14c03d95a9c2640277a33bb6
      lib_name: Movies - PVR
      collection_type: movies
      path: /media/pvr/movies
      network_path: null
      subfolder_id: null
      lib_enabled: true
    - lib_id: 6d8690fdcfbd865ddec9a7773f0014d1
      lib_name: PVR
      collection_type: tvshows
      path: /media/pvr/tv
      network_path: null
      subfolder_id: null
      lib_enabled: true
  media_managers:
    radarr:
    - url: <redacted>
      api_key: <redacted>
      # enabled: false
    sonarr:
    - url: <redacted>
      api_key: <redacted>
      # enabled: false
DEBUG: 1
...
```

### MUMC Version:

5.11.25-beta

### What Platform(s) Does This Occur On?:

Docker

### Any Additional Information You Think Will Be Useful:

```shell

```
