### ISSUE TITLE
Docker information

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#162]
### Have You Read The Wiki?:

Yes

### Describe What You Are Trying To Accomplish:

I am maybe switching to a docker installation. I was reading the documentation. I have some questions.

Docker compose example lists several environment options. Which one's are required?  Can these variables also provided with a .ENV file?  Some of the variables are also listen in the mumc_config.yaml file. Can the variables also be read from the YAML?

There is also a USER_LIBRARY_SELECTION which I cant find in the documentation. Its unclear for me what this does

### Describe What Is Happening:

preparing for docker

### MUMC Configiration File:

```yaml
services:
   mumc:
      container_name: 'mumc'
      image: ghcr.io/terrelsa13/mumc:MUMC_beta
      environment:
         TZ: 'America/New_York' # change to your timezone; required
         BRAND: 'emby' #or 'jellyfin'
         URL: 'http://localhost:8096' #or 'https://example.domain.com' or 'http://192.168.1.234:8096/emby'
         USERNAME: 'admin_username' #The setting "Allow this user to manage the server" must be selected for this user in Emby/Jellyfin
         PASSWORD: 'admin_pa$$word123' #The setting "Allow this user to manage the server" must be selected for this user in Emby/Jellyfin
         LIST_BEHAVIOR: 'blacklist' #or 'whitelist'
         MATCHING_BEHAVIOR: 'byId' #or 'byPath' or 'byNetworkPath'
         BLACKTAGS: '' #multiple tags, single string, comma separated e.g. 'blacktag1,blacktag 2,blacktag_3,blacktag-4'
         WHITETAGS: '' #multiple tags, single string, comma separated e.g. 'whitetag1,whitetag 2,whitetag_3,whitetag-4'
         MONITOR_DISABLED_USERS: true #or false
         USER_LIBRARY_SELECTION: 3 # or 2 or 1 or 0 (2, 1, and 0 require 'stdin_open: true' and 'tty: true')
         RADARR_URL: 'http://localhost:7878' #multiple urls, single string, comma separated e.g. 'https://example.domain.com,https://192.168.1.234:7878/radarr'
         RADARR_API_KEY: 'abcdef01234567899876543210fedcba' #multiple API keys, single string, comma separated e.g. 'bcadef01234567899876543210fedcba,cabdef01234567899876543210fedcba'
         SONARR_URL: 'http://localhost:8989' #multiple urls, single string, comma separated e.g. 'https://example.domain.com,https://192.168.1.234:8989/sonarr'
         SONARR_API_KEY: '9786543210fedcbaabcdef0123456789' #multiple API keys, single string, comma separated e.g. '7896543210fedcbaabcdef0123456789,8976543210fedcbaabcdef0123456789'
      volumes:
        - '/opt/MUMC/config/mumc_config.yaml:/usr/src/app/config/mumc_config.yaml' #specify the config file location on the host
        - '/opt/MUMC/logs/mumc_DEBUG.log:/usr/src/app/logs/mumc_DEBUG.log' #specify the debug log location on the host
      stdin_open: true # docker run -i
      tty: true # docker run -t
```
